theset = {"apple", "banana", "cherry"}
print(theset)
for x in theset:
    print(x)
print("banana" in theset)
theset.add("mango")
print(theset)
theset.update(["lemon", "orange"])
print(theset)
myset = theset.copy()
print(myset)
print(len(theset))
theset.remove("lemon")
print(theset)
theset.discard("berry")
print(theset)
theset.clear()
print(theset)
pset = set((1, 2, 3))
qset = myset.union(pset)
print(qset)
pset.update(pset)
print(pset)
rset = {1, 2, 3, 4, 5, 6}
z = pset.issubset(rset)
print(z)
sset = {1, 2, 3, 4, 5, 6, 7, 8}
z = sset.issuperset(rset)
print(z)
z = sset.isdisjoint(rset)
print(z)
z = sset.intersection(rset)
print(z)
z = sset.symmetric_difference(rset)
print(z)
